enum{
  EVENT_HOUR_PASS = 1,
  EVENT_RTC_UPDATE_REQUEST = 2,
  EVENT_HOUR_PUMP_PAUSE = 4,
  EVENT_HOUR_PUMP_RESUME = 0x8,
  EVENT_CMD_RCV = 0x10,	/* uart recv some data */
  EVENT_PERIOD_OPR = 0x20,
  EVENT_3 = 0x30
};
